baseURL = "https://satyajitpanda.com/"
languageCode = "en-us"
title = "Satyajit Panda"
theme = "ezhil"
paginate = 5

copyright = "Â© Copyright notice"

pygmentsstyle = "solarized-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = ""
disqusShortname = "ezhil-demo"

summaryLength = 20

[params]
	subtitle = ""
	disableDisqusTypes = ["page"]
	featherIconsCDN = true
	mode = "auto" # "dark", "auto", "light"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["https://code.jquery.com/jquery-3.4.1.js", "js/custom1.js"]  # Custom JS scripts.

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[params.social]]
name = "email"
icon = "envelope"
url = "mailto:satyajitmails@gmail.com"

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/satyajitmails"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/p_satyajit"

[[params.social]]
name = "linkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/satyajitpanda"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"
